### PR TITLE
feat: ui streamline (DOP-234)

### PR DESCRIPTION
**Pull request by hibou-de-nuit**
## Scope

Our current UI for SSOVs are fragmented into individual pages for each vault. Our new UI unifies these vaults into a single page, where users simply have to select the market based on the underlying, side (puts/calls), and expiration dates they would like to either purchase or write options.

[closes issue-DOP-234](https://linear.app/dopex/issue/DOP-234/create-the-new-ui-for-an-options-chain-which-houses-all-of-dopexs)

## Implementation

Instead of having a landing page for ssovs with cluttered cards to select from, we now have a single page to interact with all SSOVs. 

Basic flow:
- By default, we view the ETH SSOV weekly puts.
- Select asset at the top of the page
- Select option type (put/call) and duration(weekly/monthly/quarterly, etc.)
- Select a strike in the table to interact with
- Once a strike is selected, in the panel on the right hand side, select whether to purchase or deposit, and input the amount, send the txns.
- Withdraw or settle any positions that have expired in the previous epochs in the positions table below 

### **Tradeoffs**: 
- Although load times are blazing fast compared to our previous implementation, the page heavily depends on API/Subgraph to load chunks of data. If the Dopex API faces downtime, the vaults page would virtually be rendered inoperative. To rectify this, we will need to implement a fallback that makes direct calls to the contract although this can slow down the page.

### **Refactors to note**:
- Completely gets rid of mui components
- Usage of wagmi hooks for contract reads/writes
- Uses tanstack/react-table to construct table data for all tables
- Usage of custom hooks to load snippets of data from the SSOVs
- We're moving away from our previous approach to implementing zustand useBoundStore. We now use a non-asynchronous store within a custom hook to manage state. Parts of the UI are instantaneously updated thanks to this approach.

### **Note to reviewing developers**
- Overusage of useEffect() to set default states in multiple components can cause unintended side-effects.
- Wagmi hooks don't always work since config data can sometimes be undefined (eg: apps/dapp/src/components/vaults/AsidePanel/index.tsx:L110)

## How to Test

Follow the steps above.

### CODE REVIEW

**Comment by hibou-de-nuit** [comment]
Pending:
- Accordion effect for strikes chain
- Add trading view widget for selected token
- Add PnL chart in the bottom right corner.

**Comment by hibou-de-nuit** [comment]
QA Feedback:
- [ ] 1 "Sell" option option Premium APR is NaN for tokens (Aside Panel).
- [ ] 2 The buy and sell div is aligned with the buy/sell position and moves if we expand and close. Ignore if done by design. I like it this way - just informing. (Strike Chain)
- [ ] 3 Fee seems not correct (Aside panel)
- [ ] 4 Please add currency or token with fee (Aside panel)
- [ ] 5 Question: Does this mean no reward? (Yes; Blank cell in positions table)
- [ ] 6 Question: why are we showing the expired positions? If done by design we should have a filter to see only active ones coz we have both weekly and monthly. It is possible that the weekly will expire and monthly will still be there below expired ones.
- [ ] 7 Difficult to know which one is what coz same date. Like call/put we should have a label for weekly and monthly imo ( (strikes chain pills)
- [ ] 8 Expiry’s should we in descending order coz the positions which have not expired will come on top. (Positions table)
- [ ] 9 Old sell positions are being shown with clickable withdraw. I was able to withdraw one also (subgraph issue for unresponsive withdraw button)
- [ ] 10 Not able to withdraw (known subgraph issue).
- [ ] 11 Not able to settle
- [ ] 12 Question: I see 68.212 wstETH available then I see 0 steth. What is this 0 stETH? (Button shows premium, rounded to nearest 3 decimal places; 68.212 is the available liquidity for the strike)
- [ ] 13 The withdraw check converts into a check icon before the transaction completes. It should be a loading icon and only when the transaction completes it changes to a check icon. (Stepper Dialog)

**Comment by crypotto** [comment]
I can see positions which are not really there. There is settle option present which doesn’t work obviously coz the position is not there. 
image

**Comment by crypotto** [comment]
As soon as I click on approve button - the settle button becomes clickable. It should wait for the approval to happen. 

image

**Comment by hibou-de-nuit** [comment]
> As soon as I click on approve button - the settle button becomes clickable. It should wait for the approval to happen.
> 
> image

The settle transaction can be queued immediately after sending the approve -- the button only works if there is something to settle.

**Comment by crypotto** [comment]
> > As soon as I click on approve button - the settle button becomes clickable. It should wait for the approval to happen.
> > image
> 
> The settle transaction can be queued immediately after sending the approve -- the button only works if there is something to settle.

Yes, can we make it non clickable? I approved and it was there to be clicked. My position doesn’t have anything to settle. It is still clickable.

**Comment by crypotto** [comment]
For some token ex. BTC, RDPX the buy and sell pos section keeps loading forever

image

image

**Comment by crypotto** [comment]
Able to buy options now but doesn’t show on SSOV or portfolio. Txn: https://arbiscan.io/tx/0x1ea5a53df647155e595f62c9cf64f8e2d5cb9b864b1b7536b435ab5e086b444d

image

**Comment by crypotto** [comment]
We see Insufficient allowance for deposit/sell as well. I have enough balance in my wallet. 

image

**Comment by crypotto** [comment]
> Able to buy/sell options now but doesn’t show on SSOV or portfolio. Txn for buy: https://arbiscan.io/tx/0x1ea5a53df647155e595f62c9cf64f8e2d5cb9b864b1b7536b435ab5e086b444d
> 
> txn for sell: https://arbiscan.io/tx/0x21eee4d5bbbc782c56cc9155f3174f8f778aae291aad220caf349f71cc62742c
> 
> image

Shows on portfolio after some time but doesn’t show on ssov page even after refresh.

**Comment by crypotto** [comment]
I have no buy position in DPX. Why do I see this position with settle option?
 
image

**Comment by crypotto** [comment]
The Pos not updating. Ex. My ARB positions visible in STETH page.

image

**Comment by crypotto** [comment]
> > Able to buy/sell options now but doesn’t show on SSOV or portfolio. Txn for buy: https://arbiscan.io/tx/0x1ea5a53df647155e595f62c9cf64f8e2d5cb9b864b1b7536b435ab5e086b444d
> > txn for sell: https://arbiscan.io/tx/0x21eee4d5bbbc782c56cc9155f3174f8f778aae291aad220caf349f71cc62742c
> > image
> 
> Shows on portfolio after some time but doesn’t show on ssov page even after refresh.

Due to subgraph the positions are showing slow. Please add a note on pop-up saying it will take some time to reflect on the portfolio and position section.

**Pull request merged**
